# Changes here will be overwritten by Copier
_commit: 5af64c5
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: prettygoodcapital@gmail.com
github: PrettyGoodCapital
project_description: Standard financial flow models
project_name: finance flow
python_version_primary: '3.11'
team: PrettyGoodCapital
